- ScrollView:
    style:
      width: 300
      backgroundColor: '#eeeeee'
    extra_props:
      scrollToEnd: true
    children:
      - View:
          style:
            width: 200
            height: 200
            backgroundColor: white
          children:
            - HyperLink:
                url: 'https://www.vikings.com/'
                title: "Vikings"
                style:
                  letterSpacing: 18
                index: 20
      - View:
          style:
            width: 200
            height: 200
            backgroundColor: purple
          children:
            - Button:
                style:
                  width: 200
                  height: 50
                  alignItems: center
                  borderRadius: 25
                  backgroundColor: gold
                on_touch:
                  backgroundColor: rgb(255, 180, 0)
      - View:
          style:
            width: 200
            height: 200
            backgroundColor: gold
          children:
            - Button:
                style:
                  width: 200
                  height: 50
                  borderRadius: 25
                  backgroundColor: white
                on_touch:
                  backgroundColor: rgb(200, 50, 100)


